### ISSUE TITLE
Simple dapp front-end in vanilla JavaScript + Bootstrap CSS

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aip-xxx-implementation#2]
# Work plan

- [ ] Create simple dapp to display the favorite number and set the number using vanilla JavaScript + Bootstrap CSS
- [ ] Add references to README.md for any best practices followed or sources of any instructions (install steps, etc.) used
- [ ] Add screenshot to readme of working dapp (macOS + Safari, with shadows, PNG format)
- [ ] Add second screenhshot to readme showing interactivity, click the "Set Number" button and some visual feedback indicates the in-progress, and completed state (animated gif, I https://www.cockos.com/licecap/ to record)
- [ ] Complete instructions to deploy contract (mainnet, testnet, localnet, anything) and load wallet, load dapp, access in browser
  - [ ] Quality standard: one human that has interest in blockchain but zero experience programming, using a brand new 2019 MacBook Pro, successfully follows the instructions without assistance and reproduces the screenshot of the working dapp
